# Generated by Django 4.1.3 on 2022-11-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0009_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=255),
        ),
    ]
