# Generated by Django 4.1.3 on 2022-11-18 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CommentsApp', '0006_alter_reply_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='replier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_replier', to=settings.AUTH_USER_MODEL),
        ),
    ]
