# Generated by Django 4.1.3 on 2022-11-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
